spring.application.name=Servidor_API
spring.datasource.url=jdbc:mysql://lewisrp.dev:3306/Northwind
spring.datasource.username=root
spring.datasource.password=4s@wo19.+[xTrUnk@}9

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true


server.port=8080